# Generated by Django 2.2 on 2019-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190410_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='starScore',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='★', max_length=2),
        ),
    ]
