# Generated by Django 2.2.3 on 2019-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190730_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedservice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='selectedservice',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
