# Generated by Django 2.2.3 on 2019-07-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_selectedservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='services',
            field=models.ManyToManyField(to='testapp.SelectedService'),
        ),
    ]
