# Generated by Django 2.2.3 on 2019-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20190731_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='allservices',
            name='engName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
