# Generated by Django 2.2.3 on 2019-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20190731_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedservice',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
