# Generated by Django 2.2.3 on 2019-07-31 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_selectedservice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedservice',
            name='slug',
        ),
    ]
