# Generated by Django 2.2.1 on 2019-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='starScore',
            field=models.CharField(choices=[('★', '★'), ('★★', '★★'), ('★★★', '★★★'), ('★★★★', '★★★★'), ('★★★★★', '★★★★★')], default='★', max_length=10),
        ),
    ]
